change power source, adjust parser of datetime and location including error handling, exception handling of map api, and modify version numbers of LDB
StudyNightClub/livelihood-database pull request #3
Opened 2017-07-04 16:28 UTC by LucasWangGitHub

2017-07-04 16:33 UTC, ikafire commented on README.md
> +Since 6.0, livelihood_database uses sqlalchemy to handle database actions, so
Since 4.0 是"從4.0起"，這種語句不該更新版本號

2017-07-04 16:59 UTC, ikafire requested changes
大致OK，有幾個小地方要修正

2017-07-04 16:59 UTC, ikafire commented on README.md
> +Since 6.0, livelihood_database uses sqlalchemy to handle database actions, so
Since 4.0是「從4.0起」，這種語句不該更新版本號。

2017-07-04 16:59 UTC, ikafire commented on livelihood_database/datetime_parser.py
> +    # return (event_date, start_time, end_time)
不要註解老舊程式碼，直接刪掉

2017-07-04 16:59 UTC, ikafire commented on livelihood_database/location_parser.py
> +    # return sub_address.groups()
不要註解老舊程式碼，直接刪掉

2017-07-04 16:59 UTC, ikafire commented on livelihood_database/power_web_parser.py
> +INFO_REGEX = '([A-Z\da-z]*)(.+)'
底線開頭?

2017-07-04 16:59 UTC, ikafire commented on livelihood_database/power_web_parser.py
> +    # print(latitude, longitude)
寫成正式test或是另存一個檔案不要放上來
不要放這種整塊註解起來的程式碼進來

2017-07-04 16:59 UTC, ikafire commented on livelihood_database/livelihood.py
> +            timeinfo = power_web_parser.get_html_date_time(event[0], event[1], event[2])
可以考慮在 `power_web_parser.get_html_info` 就呼叫，這樣就不用分好幾個function call
簡化power_web_parser的使用

以下 `get_html_serial_number_description` 和 `get_html_address_coordinate` 也同理

2017-07-04 16:59 UTC, ikafire commented on livelihood_database/power_web_parser.py
> +            event_date = '0000-00-00'
為什麼要用這種怪日期不用 `None`
順帶一提，一般系統對datetime的實作是有範圍限制的
以MySQL為例是 '1000-01-01' to '9999-12-31'，填0000年只會讓他在進DB時爆炸

2017-07-04 16:59 UTC, ikafire commented on livelihood_database/power_web_parser.py
> +            event_start_time = '99:99:99'
一樣，為什麼不用 `None`
FYI，MySQL `TIME` 的範圍限制是 '-838:59:59' to '838:59:59'

2017-07-04 16:59 UTC, ikafire commented on livelihood_database/power_web_parser.py
> +            event_end_time = '99:99:99'
何不用 `None` 乎

2017-07-04 16:59 UTC, ikafire commented on livelihood_database/power_web_parser.py
> +            return ('000000', 'null')
`null` 和 `'null'` 是完全不同兩回事
前者是沒有值，後者是一個內容為 `'null'` ，長度為4的字串

一樣，為什麼不兩個都用 `None`

2017-07-04 16:59 UTC, ikafire commented on livelihood_database/power_web_parser.py
> +                if coordinate != (25.027223, 121.5764989):
這是啥magic number

2017-07-04 16:59 UTC, ikafire commented on livelihood_database/power_web_parser.py
> +            return (('null', 'null', 'null', 'null'), (25.027223, 121.5764989))
`'null'` != `null`
請用 `None`
後面的神奇座標又是哪來的

2017-07-04 16:59 UTC, ikafire commented on livelihood_database/power_web_parser.py
> +        return (('市', '區', '路', '象山'), coordinate)
為啥是象山
`None`

2017-07-04 19:52 UTC, LucasWangGitHub commented
需要修正的地方都改好了。

2017-07-05 01:27 UTC, ikafire approved these changes

2017-07-05 01:28 UTC, merged